// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model/message.proto

package model

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	ChanNum   int32  `protobuf:"varint,1,opt,name=chan_num,json=chanNum,proto3" json:"chan_num,omitempty"`
	Language  int32  `protobuf:"varint,2,opt,name=language,proto3" json:"language,omitempty"`
	From      string `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	To        string `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	Message   string `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Guilddbid int32  `protobuf:"varint,6,opt,name=guilddbid,proto3" json:"guilddbid,omitempty"`
	Deliverto string `protobuf:"bytes,7,opt,name=deliverto,proto3" json:"deliverto,omitempty"`
	Type      int32  `protobuf:"varint,8,opt,name=type,proto3" json:"type,omitempty"`
	Minstatus int32  `protobuf:"varint,9,opt,name=minstatus,proto3" json:"minstatus,omitempty"`
	Fromadmin int32  `protobuf:"varint,10,opt,name=fromadmin,proto3" json:"fromadmin,omitempty"`
	Noreply   bool   `protobuf:"varint,11,opt,name=noreply,proto3" json:"noreply,omitempty"`
	IsEmote   bool   `protobuf:"varint,12,opt,name=is_emote,json=isEmote,proto3" json:"is_emote,omitempty"`
	// 0 not queued, 1 queued, 2 queue full, 3 offline
	Queued int32 `protobuf:"varint,13,opt,name=queued,proto3" json:"queued,omitempty"`
	// You can specify a zone id if you want a message exclusively to one zone
	ZoneId               int32    `protobuf:"varint,14,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_0c81a9edbe69c5a4, []int{0}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetChanNum() int32 {
	if m != nil {
		return m.ChanNum
	}
	return 0
}

func (m *Message) GetLanguage() int32 {
	if m != nil {
		return m.Language
	}
	return 0
}

func (m *Message) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Message) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Message) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Message) GetGuilddbid() int32 {
	if m != nil {
		return m.Guilddbid
	}
	return 0
}

func (m *Message) GetDeliverto() string {
	if m != nil {
		return m.Deliverto
	}
	return ""
}

func (m *Message) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Message) GetMinstatus() int32 {
	if m != nil {
		return m.Minstatus
	}
	return 0
}

func (m *Message) GetFromadmin() int32 {
	if m != nil {
		return m.Fromadmin
	}
	return 0
}

func (m *Message) GetNoreply() bool {
	if m != nil {
		return m.Noreply
	}
	return false
}

func (m *Message) GetIsEmote() bool {
	if m != nil {
		return m.IsEmote
	}
	return false
}

func (m *Message) GetQueued() int32 {
	if m != nil {
		return m.Queued
	}
	return 0
}

func (m *Message) GetZoneId() int32 {
	if m != nil {
		return m.ZoneId
	}
	return 0
}

func init() {
	proto.RegisterType((*Message)(nil), "model.Message")
}

func init() { proto.RegisterFile("model/message.proto", fileDescriptor_message_0c81a9edbe69c5a4) }

var fileDescriptor_message_0c81a9edbe69c5a4 = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x91, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0x87, 0x95, 0xd0, 0x36, 0xc9, 0x01, 0x1d, 0x8c, 0x04, 0x07, 0x62, 0x88, 0x98, 0x32, 0xc1,
	0xc0, 0x33, 0x30, 0x30, 0xc0, 0x90, 0x17, 0x88, 0x5c, 0x7c, 0x04, 0x4b, 0xb1, 0x1d, 0x62, 0x1b,
	0xa9, 0x3c, 0x35, 0x8f, 0x80, 0x7c, 0x69, 0xd3, 0xed, 0x7e, 0xdf, 0xa7, 0xfb, 0x23, 0x1b, 0xae,
	0x8c, 0x53, 0x34, 0x3c, 0x19, 0xf2, 0x5e, 0xf6, 0xf4, 0x38, 0x4e, 0x2e, 0x38, 0xb1, 0x66, 0xf8,
	0xf0, 0x97, 0x43, 0xf1, 0x36, 0x0b, 0x71, 0x0b, 0xe5, 0xc7, 0x97, 0xb4, 0x9d, 0x8d, 0x06, 0xb3,
	0x3a, 0x6b, 0xd6, 0x6d, 0x91, 0xf2, 0x7b, 0x34, 0xe2, 0x0e, 0xca, 0x41, 0xda, 0x3e, 0xca, 0x9e,
	0x30, 0x67, 0xb5, 0x64, 0x21, 0x60, 0xf5, 0x39, 0x39, 0x83, 0x67, 0x75, 0xd6, 0x54, 0x2d, 0xd7,
	0x62, 0x0b, 0x79, 0x70, 0xb8, 0x62, 0x92, 0x07, 0x27, 0x10, 0x8a, 0xc3, 0x7a, 0x5c, 0x33, 0x3c,
	0x46, 0x71, 0x0f, 0x55, 0x1f, 0xf5, 0xa0, 0xd4, 0x4e, 0x2b, 0xdc, 0xf0, 0xe8, 0x13, 0x48, 0x56,
	0xd1, 0xa0, 0x7f, 0x68, 0x0a, 0x0e, 0x0b, 0xee, 0x3c, 0x81, 0xb4, 0x39, 0xec, 0x47, 0xc2, 0x92,
	0xdb, 0xb8, 0x4e, 0x1d, 0x46, 0x5b, 0x1f, 0x64, 0x88, 0x1e, 0xab, 0x79, 0xde, 0x02, 0x92, 0x4d,
	0xf7, 0x49, 0x65, 0xb4, 0x45, 0x98, 0xed, 0x02, 0xd2, 0x95, 0xd6, 0x4d, 0x34, 0x0e, 0x7b, 0x3c,
	0xaf, 0xb3, 0xa6, 0x6c, 0x8f, 0x31, 0x3d, 0x8d, 0xf6, 0x1d, 0x19, 0x17, 0x08, 0x2f, 0x66, 0xa5,
	0xfd, 0x4b, 0x8a, 0xe2, 0x1a, 0x36, 0xdf, 0x91, 0x22, 0x29, 0xbc, 0xe4, 0x79, 0x87, 0x24, 0x6e,
	0xa0, 0xf8, 0x75, 0x96, 0x3a, 0xad, 0x70, 0x3b, 0x8b, 0x14, 0x5f, 0xd5, 0x6e, 0xc3, 0x1f, 0xf0,
	0xfc, 0x1f, 0x00, 0x00, 0xff, 0xff, 0xed, 0x75, 0x5d, 0x85, 0x97, 0x01, 0x00, 0x00,
}
